### ISSUE TITLE
SendTransacationAsync always throws exceptions

### ISSUE THREAD

**Issue by ChrisSun1212** [Nethereum/Nethereum#292]
Hi,

I was testing the library with Ganachi and a simple MetaCoin smart contract from truffle.

Here is the implementation of the smart contract

contract MetaCoin {
	mapping (address => uint) balances;

	event Transfer(address indexed _from, address indexed _to, uint256 _value);

	function MetaCoin() public {
		balances[tx.origin] = 10000;
	}

	function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		Transfer(msg.sender, receiver, amount);
		return true;
	}

	function getBalanceInEth(address addr) public view returns(uint){
		return ConvertLib.convert(getBalance(addr),2);
	}

	function getBalance(address addr) public view returns(uint) {
		return balances[addr];
	}
}

When I tried to call the sendCoin function through SendTransactionAsync
var func = contract.GetFunction("sendCoin");

var result = func.SendTransactionAsync("0x627306090abaB3A6e1400e9345bC60c78a8BEf57", new object[] { "0xf17f52151EbEF6C7334FAD080c5704D77216b732", 100 }).Result;

I got an exception. base fee exceeds gas limit. However, when I test it on truffle console, everything works fine.

Any suggestion how to fix this?

Thank you very much,

Chris

**Comment by garyng2000** [comment]
I would say you are sending the default gas limit of 21000 which is almost never enough for anything other than ether transfer(i.e. all function call would fail because of out of gas). you need to use the full form(giving gas limit and/or gas price). It works in truffle most likely because truffle did a estimateGas call and set it accordingly and I don't think Nethereum do it. I have to make sure every call I do estimate then change gas limit before the actual call.

**Comment by garyng2000** [comment]
@juanfranblanco 
is that only for token transfer ? I assume in general, any generic transaction still needs to have the gasLimit/gasPrice specified in the transaction manager(default) or each individual transaction ?

**Comment by juanfranblanco** [comment]
That is for contract interaction, the other transactions (ie send Ether) use the default one.
