### ISSUE TITLE
KeyStore serialization/deserialization fails on Unity iOS

### ISSUE THREAD

**Issue by Ryo-Oka** [Nethereum/Nethereum#295]
1. `Newtonsoft.Json` assembly in `packages` throws `NotSupportedException` as dynamic code generation occurs in IL2CPP. Replacing the assembly with the latest version in https://github.com/SaladLab/Json.Net.Unity3D solves the issue, which however causes `UnityRequest` methods in `Nethereum.Unity` to fail compiling on both VS and Editor.
2. Using the new `Newtonsoft.Json` assembly on iOS build -- `KeyStoreService.EncryptAndGenerateDefaultKeyStoreAsJson()` generates a json with some properties missing: `id`, `address`, `version`, `crypto/cipher`, and `crypto/kdf`. No exception is thrown. Decrypting the json using `KeyStoreService.DecryptKeyStoreFromJson()` throws `ArgumentNullException` as those properties don't exist in it. Adding random properties to `KdfParams` class (e.g. `string foo`) solved the issue.
3. With the serialization issue fixed -- `KeyStoreService.DecryptKeyStoreFromJson()` still throws `NullArgumentException` because the json library attempts to instantiate `KdfParams` and `CryptoInfo` using their constructor parameters (which are to be used when serializing them), which include `byte[]` parameters, which obviously become null. Adding `JsonConstrutorattribute` to their parameterless constructors didn't solve the issue. Unity's `JsonUtility` cannot serialize the generics around the data structure.

**Comment by TorresLabs** [comment]
Hi, 
Did you solve this issue? I have the same problem.

**Comment by skibitsky** [comment]
@Ryo-Oka @TorresLabs try to use this one:

[Newtonsoft.Json.dll.zip](https://github.com/Nethereum/Nethereum/files/2151681/Newtonsoft.Json.dll.zip)

**Comment by juanfranblanco** [comment]
@skibitsky is that the one included? Or a different new one for AOT

**Comment by skibitsky** [comment]
@juanfranblanco a different one

**Comment by juanfranblanco** [comment]
This is the one used by Nethereum https://github.com/SaladLab/Json.Net.Unity3D

**Comment by juanfranblanco** [comment]
Quick question has anyone added the link.xml file to ensure nothing is stripped?

**Comment by TorresLabs** [comment]
Hi @juanfranblanco Since we post we have been trying different solutions.
In fact, we found a week ago the solution to use the new Json.Net.Unity3D and link.xml as you refer. But this only fix the serialisation problem. What is good because at least basic feature, like get gas price, works on IOS.
To create a wallet keystore fails (keystoreservice.EncryptAndGenerateDefaultKeyStoreAsJson) with many missing parameters, and do not create a version 3 json keystone. See bellow.
Also to decrypt a wallet fails (byte[] privateKeyBytes = keystoreservice.DecryptKeyStoreFromJson (password, keystore)) throws a json deserialisation exception, even for wallets not generated with the above procedure.
Note that everything works on Editor (Windows and Mac) and for Android.
The problem is only for IOS builds.

That is the keystone (v3) on Editor (Windows and Mac) and for Android, and it was supposed to create for the wallet using keystoreservice.EncryptAndGenerateDefaultKeyStoreAsJson.

{"address":"3e795bddec7a9bb9d81e34ea1585d2e2615a0337","crypto":{"cipher":"aes-128-ctr","ciphertext":"2eaffcbaf9f81d7ef2d10ef021a07f7bb19a023553a2abc214be581f4b97d986","cipherparams":{"iv":"caa0e5ea6f10f2ee621bfe7541bc9c44"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"535f93acb50e817d4ad3e1ac326e8cb596b2bdc1e240d60b66b4266aa1aa6321"},"mac":"0f6b2e7d1b640e23daed4b2f2ac19c2deff9ff1e3d7f9980e5b16954f264f5ea"},"id":"cf2bd28f-8ec8-4084-8ce2-985959455f43","version":3}

That is the one you get on IOS, even after solve the first issue (Json.Net.Unity3D and link.xml):

{"crypto":{"ciphertext":"152abaa36ac4ec67f409123b0edacc11085f8370ff9d82c54e080ac66ab8f647","cipherparams":{"iv":"ff621c88ed0e537f42bd6119429f1041"},"mac":"6f7cfc0f399c2ab4f82c68b2015303dae3208e0f4a73e5e313be9d95615aed60","kdfparams":{"n":262144,"r":1,"p":8,"dklen":32,"salt":"84a76276ade5899ed8ec8045d6ad73f3bf4e5f4fe0081e2d79b595b1027f8e65"}}}

The second one looks like there are some missing parameters, or is an old v1 format.

**Comment by juanfranblanco** [comment]
Many thanks for the feedback @TorresLabs, so there is still a serialisation / deserialisation problem. Ill look into changing the way this works and see if it help. Yes, you do need to use Json.Net.Unity3D which is included with the Nethereum releases and the link.xml file.

**Comment by TorresLabs** [comment]
Thanks @juanfranblanco for the support. 
In case this help, we found workaround by creating a custom class to solve the  serialisation/deserialisation issue as you can see bellow. Anyway this is a temp solution, too complicate and probably will be much better if you can solve at the library level.

<CODE>

KeyStoreService keystoreservice = new KeyStoreService ();

CustomKeyStore customKeyStore = JsonConvert.DeserializeObject<CustomKeyStore>(keystore);
customKeyStore.crypto.kdf = "scrypt";
customKeyStore.crypto.cipher="aes-128-ctr";
customKeyStore.version=3;
				
KeyStore<ScryptParams> customScryptParams=new KeyStore<ScryptParams>();
customScryptParams.Id=Guid.NewGuid().ToString();
	customScryptParams.Crypto=new CryptoInfo<ScryptParams> {
		Cipher=customKeyStore.crypto.cipher,
		CipherParams=new CipherParams{Iv= customKeyStore.crypto.cipherparams.iv},
		CipherText=customKeyStore.crypto.ciphertext,
		Kdf=customKeyStore.crypto.kdf,
		Kdfparams=new ScryptParams{
			N=customKeyStore.crypto.kdfparams.n,
			P=customKeyStore.crypto.kdfparams.p,
			R=customKeyStore.crypto.kdfparams.r,
			Dklen=customKeyStore.crypto.kdfparams.dklen,
			Salt=customKeyStore.crypto.kdfparams.salt
			},
		Mac=customKeyStore.crypto.mac	
		};
	
Nethereum.KeyStore.KeyStoreScryptService keystoreScryptService = new KeyStoreScryptService();
byte[] privateKeyBytes = keystoreScryptService.DecryptKeyStore(password, customScryptParams);
  
</CODE>

**Comment by juanfranblanco** [comment]
Yes @TorresLabs  that is exactly what I was thinking the AOT is not using the attributes in this scenario. Oddly it works on some cases. The truth is that the custom class is as good as my thought to use a custom expando object and get the values using the key strings.

**Comment by juanfranblanco** [comment]
@TorresLabs  well I eventually followed your approach as it is actually nicer than string based.
https://github.com/Nethereum/Nethereum/commit/3858dcd135cdee65739eb70487643f376705a6fd

**Comment by juanfranblanco** [comment]
You can get the latest (as in dev) from here https://github.com/Nethereum/Nethereum/tree/master/src/compiledlibraries/unitynet35dlls

**Comment by TorresLabs** [comment]
@juanfranblanco I am happy I contribute somehow to the solution.
