### ISSUE TITLE
Improve error handling for Event.DecodeAllEventsForEvent

### ISSUE THREAD

**Issue by Dave-Whiffin** [Nethereum/Nethereum#435]
The error below was caused by the 3rd field not being flagged as indexed on the DTO.

It would be preferable to have a nicer error instead of System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

``` csharp
        /*
 *     event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId);
 */
        public class TransferEvent
        {
            [Parameter("address", "_from", 1, true)]
            public string From {get; set;}

            [Parameter("address", "_to", 2, true)]
            public string To {get; set;}

            [Parameter("uint256", "_tokenId", 3, false)]
            public BigInteger TokenId {get; set;}
        }

```

**Comment by juanfranblanco** [comment]
The issue arises due to the signature hash being valid, but different number of topics.
 A simple error handling can be put in place to validate the number of topics matches the number of indexes. Although in scenarios were the signature is the same, but indexed items are not in the same order as expected might be an issue.
