### ISSUE TITLE
Raw transactions created by Nethereum not being mined on private net

### ISSUE THREAD

**Issue by MANOJKUMARCH** [Nethereum/Nethereum#456]
Hi There,

I am running a geth node and tried to perform a load testing by giving multiple transactions (1000 tx) from front end.

As the application is not crypto related and need the blocks to be mined faster, the console.go file is tweaked so that the block difficulty is always set to 1. Our case is not a crypto oriented and hence we have made the minimum gas price as 1. 

Please check and help me on it.

More details as below

#### System information

Geth
Version: 1.8.18-unstable
Git Commit: 3e1cfbae934f72c94c00e515ca872997530eede8
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.1
Operating System: linux

#### Expected behaviour

Expected behavior is  for the tx to get mined.

#### Actual behaviour

I am able to push in 1000 Tx, from front end, all the transactions are only sending 1 wei from account1 to account2. I increased nonce for the tx correctly and so there is no issue and all 1000 tx are created successfully. 

**I see the tx are struck in pending when viewed with web3.txpool**

#### Steps to reproduce the behaviour

Below is the Nethereum code used to create the 1000 tx. All the tx are created but waiting in pending queue.

				for (int i = 0; i < 1000; i++)
				{
                    string data = "Test string";	
					var gasPrice = 10+i;
					var privateKey = "XXXXXXXXXXXXXXX";
					var senderAddress = "0xa5a85c234bca3D4BF29f7Bd7AD7D458dea8Ea8E9";
					var receiveAddress = "0x1b55195c2610f7c0069cb89db1b3e973ff447a49";
					
					var txCount = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(senderAddress);
                    var nonce = txCount.Value+i;
					var value = 1;
					var encoded = Web3.OfflineTransactionSigner.SignTransaction(privateKey, receiveAddress, value, nonce, gasPrice, 100000, data.ToHexUTF8());

					Debug.WriteLine(Web3.OfflineTransactionSigner.GetSenderAddress(encoded));
					Debug.WriteLine(encoded);
					
					var txId = await web3.Eth.Transactions.SendRawTransaction.SendRequestAsync("0x" + encoded);
					var receipt = await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync(txId);
}

PS: When I worked with 10 tx before the 1000 Tx test, for the same above code, it worked fine and the tx are mined immediately.

**Comment by ConnorChristie** [comment]
One problem I see here is that you are firing and forgetting but then immediately calling `GetTransactionCount` in the next iteration. This may be a race condition between getting the transaction count and ethereum actually updating the pending / mined transaction count. Since the get transaction count method does not include txns from the txpool, the nonce could theoretically not be getting set correctly or it could be skipping nonces.

One way around this in your case could be to keep track of the nonce locally instead of relying on getting the transaction count since first off, that's going to be slow, and secondly it's not always reliable in cases where you have high throughput.

**Comment by juanfranblanco** [comment]
The Transaction Manager with the Nonce Service does that already
