### ISSUE TITLE
.NET3.5(old-Unity) deprecation?

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#520]
I just saw this:

https://twitter.com/jon_cham/status/1098257426397184005

Which means that we could remove the .NET3.5/Unity hacks/bits from Nethereum, I suppose (e.g. I've even seen binary blobs committed for this, such as in 3ed482c199c0c713576eb871cb16ec5aa50ecb06, ew!).

I was thinking to start helping on this, but then I've realised I would need to touch the nuspec files too. However, I don't see the nuspec files in the repo, where are they?

**Comment by juanfranblanco** [comment]
Until it is out of support, it will need be supported here, or maybe more. The motto is to continue support as much as we can, regardless.

The binary check in is done intentionally as they cannot be automated using nuget releases. Also CI to another repo is not supported sadly either due to dependencies.

**Comment by knocte** [comment]
Fair enough!
