### ISSUE TITLE
Get values of an address array

### ISSUE THREAD

**Issue by PavelCree** [Nethereum/Nethereum#546]
Hello, I have this property in my contract:
`address[] public offers;`
I'd like to get the values containing in this array but I don't  know how exactly I can extract them using C#.
I'm trying to get it like that 
`var contract = web3.Eth.GetContract(abi, req);`     
`var offers = contract.GetFunction("offers");`         
`var transactionHash = await offers.CallDeserializingToObjectAsync<List<Nethereum.ABI.AddressType>>();`
but the only result is the error 
> "VM Exception while processing transaction: revert"  

So the question is how to get the values from this array?

**Comment by juanfranblanco** [comment]
You will need an "string" instead of an Address type. Also check your abi and see if if the function "offers" accepts an index as you won't be able to do that. And you will have to retrieve an item at a time.

You will have to do something like this in that scenario.
offfers.CallAsync<string>(index); and get the length.

Also another option is to code generate it using one of our generators. (Although slightly different to your approach) Here is a online one http://codegen.nethereum.com to give you an idea.

If you create a function returning an array, you will be  to get the whole array at once.

**Comment by PavelCree** [comment]
Thank you, got the values :)
