### ISSUE TITLE
Nethereum.Account.dll not present on unitNet35dlls

### ISSUE THREAD

**Issue by fedecaccia** [Nethereum/Nethereum#555]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Expected Behavior
Should provide Nethereum.Accounts functions

## Current Behavior
Not present on unityNet35dlls

## Possible Solution
Add Nethereum.Accounts dlls on unityNet35dlls

## Detailed Description
I'm using Nethereum library with unityNet35dlls. I found that unityNet461dlls contains more dlls, like for example Nethereum.Accounts.dlls. I need it in order to generate a private key and public key on unity script.

**Comment by juanfranblanco** [comment]
The Nethereum.Acconts is not present in Unity3d net351 because its main function is to also create the transaction managers (specific to higher versions of .net with async / await).

Nethereum Accounts does not provide a way to create a new private key.

The following code creates a new private key.

var ecKey = Nethereum.Signer.EthECKey.GenerateKey();
var privateKey = ecKey.GetPrivateKeyAsBytes().ToHex();

You can this code to get the address 

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Signer/EthECKey.cs#L144

**Comment by juanfranblanco** [comment]
The documentation needs to be updated to reflect this as the focus on simplification has missed the Unity3d net351 scenarios.

**Comment by fedecaccia** [comment]
Thank you very much juan, your anwers have been very helpul!
