### ISSUE TITLE
Too Many Open TCP Connection

### ISSUE THREAD

**Issue by jungsid95** [Nethereum/Nethereum#606]
### Detailed Description
In my .Net Core 2.2 project, I have created an API to check eth balance using Nethereum. Each API call will open a new TCP connection to RPC and doesnt dispose it after. In linux, it will generate too many close_wait connection then eventually crash due to error of **Too many open files in system** 

![image](https://user-images.githubusercontent.com/58496109/70106657-3390b280-167f-11ea-856d-bd04213d0eb4.png)

```
ERROR 32 Microsoft.AspNetCore.Server.Kestrel - Connection id "0HLRNQKQ9FLGR", Request id "0HLRNQKQ9FLGR:00000001": An unhandled exception was thrown by the application.
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: Too many open files in system ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

### Current Behavior

![image](https://user-images.githubusercontent.com/58496109/70107092-8a4abc00-1680-11ea-97c6-be011a4b2740.png)

This will open a new connection each time but doesnt terminate or dispose it after.

### Expected Behavior
Should dispose and terminate the web3 connection

### Possible Solution
Allow to dispose the web3

**Comment by Dave-Whiffin** [comment]
Hi there.  Every Web3 instance creates an underlying HttpClient.  Typically speaking, one application should share the same HttpClient instance (at least for the same address).   We would recommend you create one web3 instance and reuse it rather than creating one every time. 

Give this a go and let me know if it resolves your issue?

**Comment by jungsid95** [comment]
> Hi there. Every Web3 instance creates an underlying HttpClient. Typically speaking, one application should share the same HttpClient instance (at least for the same address). We would recommend you create one web3 instance and reuse it rather than creating one every time.
> 
> Give this a go and let me know if it resolves your issue?

@Dave-Whiffin thank you.
The result is better than before but does not really solve the issue. Still get alot of CLOSE_WAIT

![image](https://user-images.githubusercontent.com/58496109/70218531-155dac00-177e-11ea-89c7-7212b49cc317.png)



I suspect that it is due to new httpclient is being created every 60 seconds but doesnt dispose the lold one in https://github.com/Nethereum/Nethereum/blob/d57468d09cd6892bfb132063bc840f1bd045b3b4/src/Nethereum.JsonRpc.RpcClient/RpcClient.cs

**Comment by Dave-Whiffin** [comment]
Thanks for getting back to us.  We are aware of certain challenges around this - and different versions of .net framework and core and the OS can complicate it.  I'll defer to @juanfranblanco because I think he has some potential changes in this area already lined up which are probably exactly what you need. 

For now - to unblock you, you could pass in your own IClient into the web3 constructor.  Take a copy of the source code of the existing RpcClient and amend as you wish.

**Comment by juanfranblanco** [comment]
Hi @jungsid95 why don't you try the SimpleRpcClient instead and pass your own HttpClient

**Comment by juanfranblanco** [comment]
this is the one https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.RpcClient/SimpleRpcClient.cs#L17

**Comment by jungsid95** [comment]
Thanks @juanfranblanco Will try this

**Comment by juanfranblanco** [comment]
A new RPC client / update has been created that allows the HttpClient to be used as a parameter so the lifecycle can be controlled externally.
