### ISSUE TITLE
Hello,  Is there a way to get the lowest and average price miners are asking for gas? Some statistics sites seem to have prices but they are outdated.

### ISSUE THREAD

**Issue by Adydixit** [Nethereum/Nethereum#652]
Issue tracker should be used only for reporting bugs. New features, questions and support should be discussed on our discord channel first, thanks. https://discord.gg/jQPrR58FxX

"Hello, Is there a way to get the lowest and average price miners are asking for gas? Some statistics sites seem to have prices but they are outdated."

**Comment by juanfranblanco** [comment]
@Enigmatic331 you are the expert on gas prices.

**Comment by Enigmatic331** [comment]
Your best bet is to use a gastracker site's API, e.g.

https://etherscan.io/gasTracker
https://www.gasnow.org/

Now a more thorough answer.

Lowest acceptable prices are *extremely* difficult to accurately calculate for, simply because there is a huge probability more transactions will be sent on a higher gas price (so the txpool is heavy-top), and a lot of outlier detection is needed otherwise strange gas prices like 1/6/10gwei will pop up when gas prices are supposed to be in the triple digits. The approach Etherscan uses is to rely on historically acceptable low gas prices over a timeframe with a minimal confidence requirement.

Average price depends on the algorithm - Typically you'd get some form of median, or something like a ~65 percentile-of-the-txpool. Etherscan groups txs and conservatively targets for inclusion in less than 4 minutes for its average (or proposed) recommendation while factoring in the possibility of additional txs being queued at the front, while fast recommendation aims for inclusion within the next block.
