### ISSUE TITLE
Upgrade BouncyCastle to >= 1.9.0

### ISSUE THREAD

**Issue by girishnuli** [Nethereum/Nethereum#796]
Using the latest version of Nethereum with the latest version of Mailkit is not possible due to version conflicts with BouncyCastle. It would be helpful if the BouncyCastle version used in Nethereum can be upgraded to >=1.9.0 to allow compatibility with other packages.

**Comment by juanfranblanco** [comment]
@girishnuli you see the usage of Aliases as described in this issue https://github.com/Nethereum/Nethereum/issues/791 until it gets tested and upgraded

**Comment by girishnuli** [comment]
Thanks. We have downgraded back to version 5.x for now. Hopefully this will be fixed soon.

**Comment by Salardx** [comment]
Hi, I'm waiting for this upgrade too, we need to have BouncyCastle supported above 1.9.0

**Comment by unchase** [comment]
Hi, agree with this point. Should upgrade.

**Comment by unchase** [comment]
@juanfranblanco Hi.
Could you please upload the new nuget package release?

**Comment by juanfranblanco** [comment]
[it is in nuget.org](https://www.nuget.org/) https://www.nuget.org/packages/Nethereum.Web3/

**Comment by unchase** [comment]
![image](https://user-images.githubusercontent.com/29679226/164815298-fc130f8e-b5e1-484d-b867-5bbea9e35350.png)

**Comment by unchase** [comment]
![image](https://user-images.githubusercontent.com/29679226/164879725-2de1f9fb-3c8c-4007-8abe-c15332aa8f3a.png)

**Comment by juanfranblanco** [comment]
Yes I have not tested those yet.

**Comment by juanfranblanco** [comment]
What is your usage of KeyStore?

**Comment by unchase** [comment]
I just added **Nethereum.Web3** to the project:

![image](https://user-images.githubusercontent.com/29679226/164883940-b0a28e13-2ef1-44f0-b52f-02422692b019.png)

**Comment by ManOguaR** [comment]
I found trouble using pugin systems with assembly collision prevention, with BouncyCastle version conflicts...
More concrete, trying to host Solnet side by side with Nethereum in two plugins... The system can't load both... so i just added

`<ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
		<PackageReference Include="Portable.BouncyCastle" Version="[1.9.0,2.0)" />
	</ItemGroup>`
to
'Frameworks.props'
Because some (1.1 2.0) netcore versions can't use 1.9.0

Change ` "Portable.BouncyCastle": "1.8.2"` to ` "Portable.BouncyCastle": "1.9.0"` in Nethereum.Portable projects.json

and in the project files:
Nethereum.Keystore and Nethereum.Signer: Change `  <ItemGroup Condition=" '$(TargetFramework)' != 'net35' And '$(TargetFramework)' != 'net451' And '$(TargetFramework)' != 'net461' And '$(TargetFramework)' != 'net472'">` to `<ItemGroup Condition=" '$(TargetFramework)' != 'net35' And '$(TargetFramework)' != 'net451' And '$(TargetFramework)' != 'net461' And '$(TargetFramework)' != 'net472' And '$(TargetFramework)' != 'net5.0'">`

These changes bypasses the problem for .net5.0 6.0 7.0 .... leaving untouched the backwards compatibility.
