### ISSUE TITLE
I think there is a bug in sending ftm using ftm chain

### ISSUE THREAD

**Issue by pluv242** [Nethereum/Nethereum#848]
The bug seems to happen if we use default function for sending the main currency (ftm for fantom network) in a network that doesn't support 1559 fee structure.

The bug is discussed here

https://stackoverflow.com/questions/72616326/why-i-cannot-send-ftm-with-this-simple-code?noredirect=1#comment128290320_72616326

To reproduce it you can use this code

Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
    Dim privatekey = System.IO.File.ReadAllText("privatekey.txt")
    'Dim publickey = "0x898568c58466957bedaE0e2A2457beb158a150de" ''
    Dim destination = "0x7fD0Ec4d9908A712852d32d110839Fc1A9Ce55d5"
    Dim rpcURL = "https://rpc.ftm.tools" ' where should I put this
    Dim chainID = 250 'Where should I put this?

    Dim account = New Nethereum.Web3.Accounts.Account(privatekey, chainID)
    Dim web3 = New Nethereum.Web3.Web3(account, rpcURL)
    Dim amount = New Nethereum.Hex.HexTypes.HexBigInteger(10)
    Await web3.TransactionManager.SendTransactionAsync(account.Address, destination, amount) ' bug here
End Sub

**Comment by juanfranblanco** [comment]
Your issue is that Fantom is a Fork of Ethereum and has not implemented yet the EIP-1559 pricing model. For this you have to either provide the gas price (to force legacy) or enable it in the web3.Eth.TransactionManager (Legacy)

Nethereum uses the eth_gasPrice call automatically to set the Gas Price if not provided and if it is in Legacy mode. But you should check with the Fantom chain what is the best way to get your prices.

Why do you need to pass the chainId? This is required to sign the transaction, and to ensure you know what chain you are using. (Prevent inputting the wrong url and get a replay attack).

Any other issues, please ask in discord.
