### ISSUE TITLE
Error occurred when trying to send rpc requests(s)

### ISSUE THREAD

**Issue by quitozang** [Nethereum/Nethereum#903]
In the editor and in the native player, my program is running properly and returns the expected result. But in WebGL I get the following stack trace when calling my contract's method
```
DllNotFoundException: Unable to load DLL 'libc'. Tried the load the following dynamic libraries: 
Rethrow as RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_call
  at Nethereum.JsonRpc.Client.RpcClient.SendAsync (Nethereum.JsonRpc.Client.RpcMessages.RpcRequestMessage request, System.String route) [0x00000] in <00000000000000000000000000000000>:0 
```

![image](https://user-images.githubusercontent.com/12569046/203495028-400daee2-4d01-432d-9e7a-f33ef652a29b.png)

My source code is below:
![image](https://user-images.githubusercontent.com/12569046/203495174-c728bfaf-db29-4915-8424-a39327b52f81.png)
![image](https://user-images.githubusercontent.com/12569046/203495225-3c72bdc2-0e63-4195-a1c0-7334fc588266.png)

## Expected Behavior
return the highest bidder result in my nft market contract

## Possible Solution
rpc problem in webgl?

## Context (Environment)
unity: 2021.3.10f1c1

**Comment by juanfranblanco** [comment]
When working with webgl you need to use the Unity specific libraries, check the https://github.com/Nethereum/Unity3dSampleTemplate

**Comment by rob1997** [comment]
For anyone wondering we were able to fix this issue by using [UnityWebRequestRpcTaskClient](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Unity/Rpc/UnityWebRequestRpcTaskClient.cs) for `NWeb3.Client` when initializing `NWeb3` instance.

The issue was that the default RPC client for Nethereum `Nethereum.JsonRpc.Client.RpcClient` used `System.Net.Http`
`System.Net.Http.Headers` to make Json RPC requests which is a no no in WebGL Builds so we used `UnityWebRequestRpcTaskClient` for `NWeb3.Client` instead which solved the problem.

**Comment by rob1997** [comment]
Yeah we're only using `UnityWebRequestRpcTaskClient` for Unity but I think we could even only use it for WebGL, the default `RpcClient` works for other platforms.
