### ISSUE TITLE
Implement EIP 155 simple replay attack protection

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum#91]
https://github.com/ethereum/EIPs/issues/155

**Comment by knocte** [comment]
Hey @juanfranblanco, is this not done yet? If not, I don't quite understand why my code (that uses Nethereum) is working on ETH and ETC well?

**Comment by juanfranblanco** [comment]
It remains compatible, the original EIP did not actually solve the replay issue, so I parked it. The newer version does, but I have not got around it.

**Comment by juanfranblanco** [comment]
But it is a priority (between others).

**Comment by knocte** [comment]
> The newer version

What version? Version of what?

**Comment by juanfranblanco** [comment]
Oh I'm just rambling, ignore it, talking when the EIP was created.

**Comment by knocte** [comment]
Ah right. But I thought that EIP was already enforced via hard-fork, and that's why there cannot be replay attacks anymore between ETH and ETC? Or am I wrong?

**Comment by juanfranblanco** [comment]
No, the EIP is for any chain to have an id part of the transaction signing to avoid replay across chains. Now it is not a major issue as such (if you keep different accounts in ETC and mainnet), but it will be once Plasma, sidechains support the network.

**Comment by knocte** [comment]
I have a patch for this almost ready, but before proposing it as a PR, I would like to get your input. For example, the new way to sign would receive a ChainId parameter. I've implemented this as an enum called "Chain", and each of its inner elements equals to an integer that matches the list in the spec. Where would you want to place this enum? (What assembly, what namespace?)

The answer to this can probably determine other API design choices that I'll explain later.

**Comment by juanfranblanco** [comment]
That is great :), 

I think we need the two options, an enum for known chains and the capability to pass a BigInteger (main implementation). 

Imagine in an enterprise setting,  how many chains there will be. But, it will be necessary to have some constants to enable the simple identification of known chains.

Re: Namespace, Assembly.. keep it in the signer for the time being. There is not a nice common global options yet.

**Comment by knocte** [comment]
> I think we need the two options, an enum for known chains and the capability to pass a BigInteger (main implementation).

Fair enough, although not sure if it can be as big as BigInteger, as v is just one byte.

> Re: Namespace, Assembly.. keep it in the signer for the time being.

Ok, there's a problem if I keep it in the signer. I'll try to explain:
The class Nethereum.Web3.Accounts.AccountSignerTransactionManager calls TransactionSigner.SignTransaction(), which will need to pass the ChainId parameter. How to inject this parameter? If we add it as a new parameter to the private SignAndSendTransactionAsync() method, then the method that calls it will need to receive it as well. However, if we add a "ChainId" parameter to the this caller method SendTransactionAsync() then compilation breaks because this method is marked as "override", and to change its signature, we would need to change the signature of the overriden method, which is in TransactionManagerBase class, which is in Nethereum.RPC assembly (not in Nethereum.Signer assembly).
Would you be ok, then, to make Nethereum.RPC depend on Nethereum.Signer assembly? Or should we move the Chain enum to Nethereum.RPC?

If you don't like any of the options above, there's a third option: pass the ChainId to the constructor of AccountSignerTransactionManager, but I tried to go this route, and found myself needing to pass ChainId to the Account class because of other existing design decisions (which I can explain further if you want, but this 3rd option is the ugliest one in my opinion... too much API breakage...).

**Comment by juanfranblanco** [comment]
The new spec makes it a BigInteger, it was in one of the comments.

Regarding the signers. there is going to be 2 signers now. 

The original which it will be the default for the transaction manager and the new signer, which will be used when a ChainId is present.

The TransactionManager can have a property ChaindId.

Web3 will have a ChainId property which will set the TransactionManager and anything that needs it afterwards.

Web3 could be the one having a SetChainId accepting the Enum, and Chains enum can live in Web3? 

As other blockchain components are finished / implemented it can move to another Assembly.

**Comment by juanfranblanco** [comment]
So the transaction manager can act as the orchestrator temporarily of the signers, but it could be a signer Factory that instantiates on demand based on the chainid.

**Comment by knocte** [comment]
> The new spec makes it a BigInteger, it was in one of the comments.

Not sure how this would work, but if you don't mind we can leave this possibility for a subsequent PR (which introduces a specific test that uses a very big v), as I have my PR ready now (main test green).

> Web3 could be the one having a SetChainId accepting the Enum, and Chains enum can live in Web3?

I don't mind placing Chain enum in N.Web3, however, I'm not a fan of setting properties. First, because it brings mutation, and second, because it would need a default behaviour for when the consumer doesn't call the setter (mainnet?). I would prefer if we pass ChainId in the Web3 constructor, and then it has a Chain public getter (private setter, only used at ctor time). How about that?

**Comment by juanfranblanco** [comment]
> Not sure how this would work, but if you don't mind we can leave this possibility for a subsequent PR (which introduces a specific test that uses a very big v), as I have my PR ready now (main test green).

Of course

> I don't mind placing Chain enum in N.Web3, however, I'm not a fan of setting properties. First, because it brings mutation, and second, because it would need a default behaviour for when the consumer doesn't call the setter (mainnet?). I would prefer if we pass ChainId in the Web3 constructor, and then it has a Chain public getter (private setter, only used at ctor time). How about that?

And default constructor as now, will use the current signer?

**Comment by knocte** [comment]
> And default constructor as now, will use the current signer?

Not sure what you mean. All Web3() constructors would need to receive a Chain/ChainId parameters. But I'm having a big of trouble trying to make everything work by passing a Chain parameter to Web3 constructors. There are too many implications for this change, which have cascading effects which will probably make your review longer than expected. So I was thinking...

> As other blockchain components are finished / implemented it can move to another Assembly.

I'll take this advice from above, just to get the new EIP signing logic merged and reviewed quickly. To do this, and make the less changes possible, Chain enum will probably live in a place that you may not like. However, I'm thinking you could not make any new Nethereum release, until you have moved it somewhere else, with the necessary refactorings to do this.

I mean, I don't have any urgency on getting this reviewed/merged/released, but I guess you don't mind uploading a pre-release to Nuget so that my client can depend on it until the API gets stable (and releasable) again.

**Comment by juanfranblanco** [comment]
All Web3 constructors won't need to change as they can default to current signer for backwards compatibility. The Enum namespace / location can change, later on, I would not worry too much.

**Comment by knocte** [comment]
Ok that makes sense. This is my work in progress FYI: https://github.com/knocte/Nethereum/commits/eip155 . The meat of the change is this one: https://github.com/knocte/Nethereum/commit/478cae095b200593cb79ea6d6814221e0612f4e0 , but I still need to work on the last commit (the one to make everything build again) because it's horrible.

**Comment by juanfranblanco** [comment]
Do you mind if I have a go this weekend? Mainly the steps will be ( I can concentrate on the signer part )
- [ ] Create an inherited signer (ChainTransactionSigner, AKA as Chain Signer below) from TransactionSigner
- [ ] Make virtual the Sign etc, so they can be specialised on TransactionSigner.
- [ ] Chain signer will be instantiated with a ChainId (let's say number for now / bytes)
- [ ] Chain signer, extend sign to: Include new V calculation, and hashing mechanism extended to include ChainID, R, S
- [ ] Chain signer, recovery from signature and ChainId validation
- [ ] Transaction manager will be instantiated with either a ChainId (BigInteger) or nothing, with a ChainId will use the ChainTransactionSigner. ChainId will be property (getter only) so it is unmutable.
- [ ] Account will also use the ChainId as a constructor, and Account belongs to a Chain :). 
- [ ] I have a todo to move the Account to another assembly, we could put chains there for the time being.

**Comment by juanfranblanco** [comment]
@knocte  see above: (Keeping it here the comments as opposed to adding comments to the)

From your commit without merging we can grab:

+ The tests and separation.
+ The V calculation based on ChainId.

**Comment by knocte** [comment]
> From the EIP, so it is not Legacy.
>`` The currently existing signature scheme using v = 27 and v = 28 remains valid and continues to operate under the same rules as it does now. ```

I disagree. The fact that it remains valid is to make sure backwards compatibility exists, but the libraries should stop providing the old way of signing because it's dangerous, as it's vulnerable to replay attacks (I realized this myself when I implemented single-key generation for my multi-currency wallet, and later figured this would make ETC&ETH payments unsafe).

**Comment by juanfranblanco** [comment]
Yes and no (Depends as usual)

If you are working in an enterprise chain and create new accounts for that chain. There is a major risk associated trusting you are protected by using chainIds as these may collide, imagine how many millions of chains can be in the future (In the Enterprise) and how do you know which chain is using which chain Id. 

Isolated chains should not reuse accounts if they cannot ensure uniqueness of a chainId. So believing this is a protection is naive.

Now if chainIds are random BigInteger created in the same way as accounts, yes that is a good case. BUT your transaction size will grow significantly. Hence I am keen on the BigInteger.

The Yes part, if you are going to share accounts between public chains. Totally.

With Plasma, Sidechains if you are going to use the same Account too. Also, a rogue side / plasma chain might trick users to use the same chainId.

**Comment by juanfranblanco** [comment]
In general, with multiple identities, you are more protected.

**Comment by knocte** [comment]
> Do you mind if I have a go this weekend?

Sure, but do you mind adding your changes on top of my commit? Because I plan to keep working on this (I'll add more tests) the next days. This way we don't step on each other's toes.

> Transaction manager will be instantiated with either a ChainId (BigInteger) or nothing, with a ChainId will use the ChainTransactionSigner. ChainId will be property (getter only) so it is unmutable.

Sure, just make sure that the way to instantiate without ChainId makes it a warning for the consumer of Nethereum (with an Obsolete attribute)?

> Account will also use the ChainId as a constructor, and Account belongs to a Chain :).

Sounds good, and actually in one of my first versions of the patch I was doing this, but later thought you would not agree with it.

> I have a todo to move the Account to another assembly, we could put chains there for the time being.

Sounds good.

**Comment by juanfranblanco** [comment]
```
Sure, but do you mind adding your changes on top of my commit? Because I plan to keep working on this (I'll add more tests) the next days. This way we don't step on each other's toes.
```
I am going to revert lots of stuff, Obsolete included as per my comments above.

**Comment by knocte** [comment]
> There is a major risk associated trusting you are protected by using chainIds as these may collide, imagine how many millions of chains can be in the future (In the Enterprise) and how do you know which chain is using which chain Id.

You're not disagreeing with me, you're just bringing up that EIP155 with simple ChainIds is not bullet-proof. To protect from this, you would maybe need to provide an overload that not only accepts BigInteger for ChainId, but maybe rather a GUID, to make sure it's randomly generated, and then mark the (int chainId) overload as Obsolete deeming it as unsafe as well. I don't see how your argument favors removing the Obsolete attribute, but rather encourages it.

**Comment by juanfranblanco** [comment]
Also note that the simple rlp signer is a generic class for Rlp signing, it does not need to be related to a chain.

**Comment by juanfranblanco** [comment]
Oh, my point is that the Simple Replay attack protection is mainly that a simple replay attack. Having 1 account per chain is the best you can do. ChainIds are great for forks, if you plan to keep the same account (you shouldn't)

**Comment by juanfranblanco** [comment]
```But when to include v,r,s in the raw hash is determined by the EIP, and that logic is inside the RlpSigner.```

No that is for Transaction signing. I can create RLP messages that are not related to a chainid and sign them.

```"You shouldn't" -> This is a good generic advice, but if you're a wallet vendor, for example, that supports many currencies, having one single seed for all of them is a good feature.```

If you are a generic vendor using a multiple currency wallet, you are creating accounts per each currency anwyay. i.e Bitcoin, etc. already.

**Comment by knocte** [comment]
> If you are a generic vendor using a multiple currency wallet, you are creating accounts per each currency anwyay. i.e Bitcoin, etc. already.

That argument only applies when we're talking about chains with different architectures. But between ETH and ETC, if you use the same seed, then you end up with the same public key and hence address (so vulnerable to replay attack). I've thought about overwriting the last byte of the private key with a chain identifier after decrypting the seed, but if I do this I'd make the seed feature incompatible with other wallets (or BIP/EIP standards).

**Comment by juanfranblanco** [comment]
I'll start from the classes structure and push stuff now very quickly so you get an idea. Give me a couple of hours. Might as well pause on the code generator and get this done, I want it to get it out of the way for you as you have started the effort.

```move the Sign method to (Chain)TransactionSigner classes.```

Yes, that is what I said about keeping the tests, and Sign method from your commit as it calculates the new V using the ChainId. But there is lots TODO here, the message is not completed, r and v not included, recovery etc.  That is the stuff that take longer.

**Comment by juanfranblanco** [comment]
I am reorganising the projects and unit tests, before this. 2 hours more :)

**Comment by knocte** [comment]
What timezone are you on? doesn't look like UK :)

**Comment by juanfranblanco** [comment]
UK, I do wake up early :) Refactoring tests still, I am so good estimating.

**Comment by knocte** [comment]
I know, I'll never be good at estimation and I hate when somebody asks me about it x-)

So I've seen a lot of refactoring commits, what do you reckon should be the next steps?

**Comment by juanfranblanco** [comment]
@knocte latest it has a signer working now. TODO after lunch include it in the TransactionManager / Account.  Vs are byte[] to support BigIntegers. Hopefully, when you read this I have done the other part.

**Comment by juanfranblanco** [comment]
I have pushed now the end to end "solution".
You can now in simple terms do:

var web3 = new Web3(new Account(privateKey, 4500));
4500 is the chainId, or use your enum (I have left it / copied it to the Signer project from the pull).

If you run clique from testchain, it is preconfigured to that chain.

Let me know how it goes, and any feedback.

**Comment by knocte** [comment]
Looks cool so far, I've only found a few nitpicks, so I'll wrap those on a follow-up PR (better to not release anything on nuget yet).

**Comment by juanfranblanco** [comment]
Nice, I appreciate all the feedback (and testing).

**Comment by knocte** [comment]
@juanfranblanco do you mind publishing a new nuget version now? I'll give it a go and if I don't see problems we can close this.

**Comment by knocte** [comment]
I confirmed that, with v2.3.1 and using ETH chainID, sending to an ETC server fails, and viceversa (using ETC chain ID sending to an ETH server fails), with an account that had both ETH and ETC (same public address, so vulnerable to replay attack). So you can close this!

**Comment by juanfranblanco** [comment]
Thanks @knocte :)
